name: Run MATLAB Script on GitHub-Hosted Runner
on: [push, pull_request]
jobs:
  job1:
    name: Run on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v0
        with:
          release: R2020a
      - name: Run script
        uses: matlab-actions/run-command@v0
        with:
          command: myfunc(2)
      - name: Run tests
        uses: matlab-actions/run-tests@v0
